### ISSUE TITLE
Can not compile this code

### ISSUE THREAD

**Issue by liufujun135** [openbmc/ipmitool#1]
It has no configure and makefile.in files. So I can not compile this code completely.

In addition, how to fix this error:
dbus.c:43:28: fatal error: systemd/sd-bus.h: No such file or directory
 #include <systemd/sd-bus.h>

Thanks.

**Comment by jk-ozlabs** [comment]
> It has no configure and makefile.in files. So I can not compile this code completely.

You'll need to run the `bootstrap` script to create the configure script.

**Comment by liufujun135** [comment]
hi Jeremy，

Thanks for your quick response.
It is ok now.

**Comment by jk-ozlabs** [comment]
Great!
